runtime: python39
env: standard
instance_class: F1

handlers:
- url: .*
  script: auto

env_variables:
  PORT: '8080'

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

