options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/devops-442409/alexjelani/gcp-pipeline-2-appengine:$COMMIT_SHA', '.']
  
  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['app', 'deploy']

images:
  - 'gcr.io/devops-442409/alexjelani/gcp-pipeline-2-appengine:$COMMIT_SHA'

